# Generated by Django 6.0.4 on 2026-04-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('mandoub', 'مندوب'), ('ouvrier', 'عامل مندوبية'), ('charge_application', 'مكلف بالتطبيقة'), ('responsable', 'مسؤول / إداري')], max_length=30, verbose_name='الفئة')),
                ('nom', models.CharField(max_length=100, verbose_name='اللقب')),
                ('prenom', models.CharField(max_length=100, verbose_name='الاسم')),
                ('sexe', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('date_naissance', models.DateField(verbose_name='تاريخ الميلاد')),
                ('lieu_naissance', models.CharField(max_length=150, verbose_name='مكان الميلاد')),
                ('nin', models.CharField(max_length=18, unique=True, verbose_name='رقم التعريف الوطني (NIN)')),
                ('telephone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('adresse', models.TextField(verbose_name='العنوان')),
                ('commune', models.CharField(max_length=100, verbose_name='البلدية')),
                ('wilaya', models.CharField(choices=[('01', 'أدرار'), ('02', 'الشلف'), ('03', 'الأغواط'), ('04', 'أم البواقي'), ('05', 'باتنة'), ('06', 'بجاية'), ('07', 'بسكرة'), ('08', 'بشار'), ('09', 'البليدة'), ('10', 'البويرة'), ('11', 'تمنراست'), ('12', 'تبسة'), ('13', 'تلمسان'), ('14', 'تيارت'), ('15', 'تيزي وزو'), ('16', 'الجزائر'), ('17', 'الجلفة'), ('18', 'جيجل'), ('19', 'سطيف'), ('20', 'سعيدة'), ('21', 'سكيكدة'), ('22', 'سيدي بلعباس'), ('23', 'عنابة'), ('24', 'قالمة'), ('25', 'قسنطينة'), ('26', 'المدية'), ('27', 'مستغانم'), ('28', 'المسيلة'), ('29', 'معسكر'), ('30', 'ورقلة'), ('31', 'وهران'), ('32', 'البيض'), ('33', 'إليزي'), ('34', 'برج بوعريريج'), ('35', 'بومرداس'), ('36', 'الطارف'), ('37', 'تندوف'), ('38', 'تيسمسيلت'), ('39', 'الوادي'), ('40', 'خنشلة'), ('41', 'سوق أهراس'), ('42', 'تيبازة'), ('43', 'ميلة'), ('44', 'عين الدفلى'), ('45', 'النعامة'), ('46', 'عين تيموشنت'), ('47', 'غرداية'), ('48', 'غليزان'), ('49', 'تيميمون'), ('50', 'برج باجي مختار'), ('51', 'أولاد جلال'), ('52', 'بني عباس'), ('53', 'عين صالح'), ('54', 'عين قزام'), ('55', 'تقرت'), ('56', 'جانت'), ('57', 'المغير'), ('58', 'المنيعة')], max_length=2, verbose_name='الولاية')),
                ('rib', models.CharField(blank=True, max_length=23, null=True, verbose_name='رقم الحساب البنكي (RIB)')),
                ('banque', models.CharField(blank=True, max_length=100, null=True, verbose_name='البنك')),
                ('poste', models.CharField(max_length=150, verbose_name='المنصب')),
                ('mission', models.TextField(blank=True, null=True, verbose_name='المهمة')),
                ('date_debut', models.DateField(verbose_name='تاريخ بداية العمل')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العمل')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='الصورة الشخصية')),
                ('role_systeme', models.CharField(choices=[('admin', 'مدير النظام'), ('editeur', 'محرر'), ('lecteur', 'قارئ')], default='lecteur', max_length=20, verbose_name='صلاحية النظام')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('actif', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'الأشخاص',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
