# Generated by Django 6.0.4 on 2026-04-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='fax',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='فاكس'),
        ),
        migrations.AddField(
            model_name='personne',
            name='telephone2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم هاتف ثانوي'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='telephone',
            field=models.CharField(max_length=10, verbose_name='رقم الهاتف'),
        ),
    ]
